[package]
name = "oni-client"
version.workspace = true
edition.workspace = true
publish.workspace = true

[[bin]]
name = "oni-spacewar"
path = "src/main.rs"

[dependencies]
sim.workspace = true
content.workspace = true
bevy.workspace = true
bevy_ggrs.workspace = true
ggrs.workspace = true
matchbox_socket.workspace = true
serde.workspace = true
serde_json.workspace = true
bincode.workspace = true
